package ai.cellbots.common.data;

import com.google.firebase.database.Exclude;
import com.google.firebase.database.PropertyName;

/**
 * Data type for the position of the robot from the Firebase database.
 */

public class RobotPreferences {

    public static final double DEFAULT_MAX_GOAL_DISTANCE_FROM_ADF = 1.0;
    public static final double DEFAULT_GOAL_TIMEOUT_SECONDS = 30.0;
    public static final double DEFAULT_SMOOTHER_DEVIATION = 0.1;
    public static final double DEFAULT_SMOOTHER_SMOOTHNESS = 0.3;
    public static final int DEFAULT_INFLATION_DISTANCE_CM = 30;
    public static final int DEFAULT_SEEKBAR_PERCENTAGE = 100;

    public static final boolean DEFAULT_USE_OCTOMAP = false;
    public static final boolean DEFAULT_IMPORT_MAPS = true;
    public static final boolean DEFAULT_ADJUST_POSES = false;
    public static final boolean DEFAULT_AUTOGEN_SOUNDS = true;
    public static final boolean DEFAULT_USER_SOUNDS = true;
    public static final boolean DEFAULT_COMMANDS_SOUNDS = true;

    @PropertyName("useOctomap")
    public boolean mUseOctomap;
    @PropertyName("importWorlds")
    public boolean mImportWorlds;
    @PropertyName("bundleAdjustment")
    public boolean mBundleAdjustment;
    @PropertyName("enableSoundsAutoGeneratedGoals")
    public boolean mEnableSoundsAutoGeneratedGoals;
    @PropertyName("enableSoundsUserGeneratedGoals")
    public boolean mEnableSoundsUserGeneratedGoals;
    @PropertyName("enableSoundsCommands")
    public boolean mEnableSoundsCommands;
    @PropertyName("maxDistanceGoalFromADF")
    public double mMaxDistanceGoalFromADF;
    @PropertyName("goalTimeout")
    public double mGoalTimeout;
    @PropertyName("smootherDeviation")
    public double mSmootherDeviation;
    @PropertyName("smootherSmoothness")
    public double mSmootherSmoothness;
    @PropertyName("maxLinearVelocity")
    public int mMaxLinearVelocity;
    @PropertyName("occupancyGridInflation")
    public int mOccupancyGridInflation;

    public RobotPreferences() {
        mUseOctomap = DEFAULT_USE_OCTOMAP;
        mImportWorlds = DEFAULT_IMPORT_MAPS;
        mBundleAdjustment = DEFAULT_ADJUST_POSES;
        mEnableSoundsAutoGeneratedGoals = DEFAULT_AUTOGEN_SOUNDS;
        mEnableSoundsUserGeneratedGoals = DEFAULT_USER_SOUNDS;
        mEnableSoundsCommands = DEFAULT_COMMANDS_SOUNDS;
        mMaxDistanceGoalFromADF = DEFAULT_MAX_GOAL_DISTANCE_FROM_ADF;
        mMaxLinearVelocity = DEFAULT_SEEKBAR_PERCENTAGE;
        mGoalTimeout = DEFAULT_GOAL_TIMEOUT_SECONDS;
        mSmootherDeviation = DEFAULT_SMOOTHER_DEVIATION;
        mSmootherSmoothness = DEFAULT_SMOOTHER_SMOOTHNESS;
        mOccupancyGridInflation = DEFAULT_INFLATION_DISTANCE_CM;
    }

    // TODO(shokman): we need to encapsulate all preferences into its own class
    // TODO Follow issue here https://github.com/cellbotsai/RobotsideApp/issues/337
    public RobotPreferences(boolean useOctomap,
            boolean importWorlds, boolean bundleAdjustment,
            boolean enableSoundsAutoGeneratedGoals, boolean enableSoundsUserGeneratedGoals,
            boolean enableSoundsCommands, double maxDistanceGoalFromADF, int maxLinearVelocity,
            double goalTimeout, double smootherDeviation, double smootherSmoothness,
            int occupancyGridInflation) {

        mUseOctomap = useOctomap;
        mImportWorlds = importWorlds;
        mBundleAdjustment = bundleAdjustment;
        mEnableSoundsAutoGeneratedGoals = enableSoundsAutoGeneratedGoals;
        mEnableSoundsUserGeneratedGoals = enableSoundsUserGeneratedGoals;
        mEnableSoundsCommands = enableSoundsCommands;
        mMaxDistanceGoalFromADF = maxDistanceGoalFromADF;
        mMaxLinearVelocity = maxLinearVelocity;
        mGoalTimeout = goalTimeout;
        mSmootherDeviation = smootherDeviation;
        mSmootherSmoothness = smootherSmoothness;
        mOccupancyGridInflation = occupancyGridInflation;
    }

    @Exclude
    @Override
    public String toString() {
        return "Robot{" +
                "Use Octomap='" + mUseOctomap + '\'' +
                ", Import Worlds='" + mImportWorlds + '\'' +
                ", Bundle Adjustment='" + mBundleAdjustment + '\'' +
                ", Enable Sounds Autogenerated Goals='" + mEnableSoundsAutoGeneratedGoals + '\'' +
                ", Enable Sounds User Generated Goals='" + mEnableSoundsUserGeneratedGoals + '\'' +
                ", Enable Sounds Commands='" + mEnableSoundsCommands + '\'' +
                ", Max Distance Goal From ADF='" + mMaxDistanceGoalFromADF + '\'' +
                ", Max Linear Velocity='" + mMaxLinearVelocity + '\'' +
                ", Goal Timeout='" + mGoalTimeout + '\'' +
                ", Smoother Deviation='" + mSmootherDeviation + '\'' +
                ", Smoother Smoothness='" + mSmootherSmoothness + '\'' +
                ", Occupancy Grid Inflation=" + mOccupancyGridInflation +
                '}';
    }
}
